data(cars)
str(cars)
attach(cars)
plot(speed,dist)
grid()
layout(matrix(c(1,1,2,3,4,2),3,2))
plot(speed,dist)
grid(ny=7,nx=0)
plot(speed,dist)
plot(speed,dist)
plot(speed,dist)
grid()
layout(matrix(1,1,1))#reset to one plot per device
plot(speed,dist)
rug(speed)
grid()

layout(matrix(c(1,2),2,1))
plot(speed,dist)
plot(speed,dist)
